CREATE TABLE IF NOT EXISTS USERS (
    ID UUID NOT NULL UNIQUE,
    LOGIN VARCHAR(20) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    birth_date DATE NOT NULL,
    NAME VARCHAR(255) NOT NULL,
    address VARCHAR(255) NOT NULL,
    technology VARCHAR(20) NOT NULL,
    reputation INT NOT NULL,

    PRIMARY KEY (ID)
);