CREATE TABLE IF NOT EXISTS CONTENTS (
    ID BIGINT NOT NULL UNIQUE,
    TITLE VARCHAR(255) NOT NULL,
    DURATION INT NOT NULL,
    technology VARCHAR(20) NOT NULL,
    level VARCHAR(20) NOT NULL,

    COURSE_ID INT,

    FOREIGN KEY (COURSE_ID) REFERENCES COURSES(id),

    PRIMARY KEY (ID)
);